# Site settings
title: Layout Patterns
author: Taylor Edwards
authorsite: www.tayloredwards.net
email: me@tayloredwards.net
description: >
             Layouts form the foundation of design on the web. 
             This project organizes them as patterns and provides
             vocabulary to discuss them.
baseurl: ""
url: "http://layoutpatterns.com"
twitter_username: rumudiez
github_username:  rumudiez

collections:
  case-studies:
    output: true

# Build settings
markdown: kramdown
