# Site settings
title: Layout Patterns
author: Taylor Edwards
authorsite: www.tayloredwards.net
email: me@tayloredwards.net
description: Layouts form the foundation of design on the web. They can be considered as patterns and used as a method of both evaluation and exploration.
baseurl: ""
url: "http://layoutpatterns.com"
twitter_username: rumudiez
github_username:  rumudiez

collections:
  case-studies:
    output: true

# Build settings
markdown: kramdown
